### ISSUE TITLE
Backend - Set up database

### ISSUE THREAD

**Issue by ZzRanger** [ZzRanger/Compass#1]
**Tasks**
- [x] Choose a database
- [x] Set it up & connect to backend.
- [ ] Write logic to perform all CRUD operations on the database.

**Comment by Buchimi** [comment]
We will be using Postgress as the database.

Rust crate for [async postgress](https://lib.rs/crates/tokio-postgres)

Here's a crate for [sync postgress](https://lib.rs/crates/postgres)

**Comment by Buchimi** [comment]
I had to use a Docker server hosting postgress
Check [this tutorial](https://tms-dev-blog.com/postgresql-database-with-rust-how-to/) out for how i did it 
I will prefer to have an async runtime though



![Image](https://user-images.githubusercontent.com/61808599/172308417-e700a144-f4d9-4573-93ba-624bf469a9ad.png)

**Comment by Buchimi** [comment]
Ok, so I got tokio-postgress (the async version to work)

## Steps
- Get docker and docker compose
- create a docker-compose.yaml file with these configurations
`version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=dboperator
      - POSTGRES_PASSWORD=operatorpass123
      - POSTGRES_DB=postgres
    ports:
      - "5243:5432"`


![Image](https://user-images.githubusercontent.com/61808599/172313389-481ff8ca-b2b7-4691-835e-22d105147ee4.png)


- run docker-compose up
  - Your shell should look like this
  

![Image](https://user-images.githubusercontent.com/61808599/172312168-a0f1702f-e86d-4e56-98d4-c67c39f96d1a.png)


  - Note the name of the database the arrow points to
  - You can test if the db is up using the `docker ps` command
  - then use this command 
  - `docker exec -ti compass-postgres-1  bash` to interface with the container and 
  - `psql -d postgres -U dboperator` to interface with postgress
  - the use `\list` to get a list of the running databases. Note the name "postgress"
- With that done you can have this in your main function
- 

![Image](https://user-images.githubusercontent.com/61808599/172313161-0978092f-39d1-4afe-9a61-29add29ce2c2.png)


- Code is here for copy and paste:
#[tokio::main] // By default, tokio_postgres uses the tokio crate as its runtime.
async fn main() -> Result<(), Error> {
    // Connect to the database.
    let (client, connection) =
        tokio_postgres::connect("postgresql://dboperator:operatorpass123@localhost:5243/postgres", NoTls).await?;

    // The connection object performs the actual communication with the database,
    // so spawn it off to run on its own.
    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("connection error: {}", e);
        }
    });

    Ok(())
}

## Check the string in the connect method
"postgresql://dboperator:operatorpass123@localhost:5243/postgres"
"protocol?:// Username : Password @url : port_no / name _of_db"

Also for @jmyrick02 
We can replace the artix::main macro with the tokio::main macro because artix runs on top of tokio

**Comment by jmyrick02** [comment]
Hey great work @Buchimi 
I will look into this further later this week as I've been busy. Have you looked at Diesel? The actix documentation on databases uses it and there are examples with postgres. I believe it is an abstraction on directly working with tokio although I haven't had much of a chance to look into it. If you haven't already, look into it, it would be good if we could use it to simplify development a bit. I'll be looking at your findings and Diesel soon.

https://actix.rs/docs/databases/
